### ISSUE TITLE
App crashes with NPE when getting Bluetooth devices

### ISSUE THREAD

**Issue by sibbl** [ClusterM/sony-headphones-control#1]
On my Pixel 3 with Android 10 the all crashes with the following exception:

```
FATAL EXCEPTION: main
Process: com.clusterrr.sonyheadphonescontrol, PID: 14490
java.lang.NullPointerException: Attempt to get length of null array
	at com.clusterrr.sonyheadphonescontrol.TaskerFireReceiver.sendData(TaskerFireReceiver.java:133)
	at com.clusterrr.sonyheadphonescontrol.TaskerFireReceiver.setAmbientSound(TaskerFireReceiver.java:122)
	at com.clusterrr.sonyheadphonescontrol.TaskerFireReceiver.execute(TaskerFireReceiver.java:91)
	at com.clusterrr.sonyheadphonescontrol.MainActivity.onClick(MainActivity.java:110)
	at android.view.View.performClick(View.java:7140)
	at android.view.View.performClickInternal(View.java:7117)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27351)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by sibbl** [comment]
I've opened PR #2 which fixes it for me.

**Comment by ClusterM** [comment]
Great work, thank you!
